name = "Hinode"
license = "MIT"
licenselink = "https://github.com/gethinode/hinode/blob/main/LICENSE"
description = "All about AI for 6G"
homepage = "https://aiforwireless.org"

tags = ["5G", "AI", "6G"]
min_version = "0.120.0"

[author]
  name = "Santosh Ganji"
  homepage = "https://github.com/shotsan"
