[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20



[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 10

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

#[[sample]]
 # name = "Projects"
  #pageRef = "/projects/"
  #weight = 20

#[[sample]]
#  name = "Sample project"
 # pageRef = "/projects/sample-project/"
  #parent = "Projects"
  #weight = 1

# toml-docs-end sample-navigation
